/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesOfferingIdRouteImport } from './routes/companies.$offeringId'
import { Route as ApiTpoSplatRouteImport } from './routes/api/tpo.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesOfferingIdRoute = CompaniesOfferingIdRouteImport.update({
  id: '/$offeringId',
  path: '/$offeringId',
  getParentRoute: () => CompaniesRoute,
} as any)
const ApiTpoSplatRoute = ApiTpoSplatRouteImport.update({
  id: '/api/tpo/$',
  path: '/api/tpo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/companies/$offeringId': typeof CompaniesOfferingIdRoute
  '/api/tpo/$': typeof ApiTpoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/companies/$offeringId': typeof CompaniesOfferingIdRoute
  '/api/tpo/$': typeof ApiTpoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/companies/$offeringId': typeof CompaniesOfferingIdRoute
  '/api/tpo/$': typeof ApiTpoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/settings'
    | '/companies/$offeringId'
    | '/api/tpo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/settings'
    | '/companies/$offeringId'
    | '/api/tpo/$'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/settings'
    | '/companies/$offeringId'
    | '/api/tpo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiTpoSplatRoute: typeof ApiTpoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$offeringId': {
      id: '/companies/$offeringId'
      path: '/$offeringId'
      fullPath: '/companies/$offeringId'
      preLoaderRoute: typeof CompaniesOfferingIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/api/tpo/$': {
      id: '/api/tpo/$'
      path: '/api/tpo/$'
      fullPath: '/api/tpo/$'
      preLoaderRoute: typeof ApiTpoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesOfferingIdRoute: typeof CompaniesOfferingIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesOfferingIdRoute: CompaniesOfferingIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiTpoSplatRoute: ApiTpoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
